### PR TITLE
Changed way to use env variables

### PR DESCRIPTION
**Pull request by rajatguptarg**

### CODE REVIEW

**Comment by gosuri** [comment]
@rajatguptarg What's the reason for this change?

**Comment by rajatguptarg** [comment]
Because this notation which was given in the earlier documentation was not working properly/

**Comment by gosuri** [comment]
We use it every day, it works for us. More over, this is the main feature
of the plugin — updating the docs won't fix what ever issue you may have.

Sorry, I cannot accept this patch.

**Comment by gosuri** [comment]
Alternatively, you could open an issue with your environment details, which is most likely the culprit --
may be we can help you resolve.

**Pull request closed without merging**
